// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package analytics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[HumanGo-1]
	_ = x[GeneratedGo-2]
	_ = x[TestGo-3]
}

const _FileType_name = "UnknownHumanGoGeneratedGoTestGo"

var _FileType_index = [...]uint8{0, 7, 14, 25, 31}

func (i FileType) String() string {
	if i < 0 || i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
